version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - nuxt
  
  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:8.12
    environment:
      NODE_ENV: development
    volumes:
      - ./:/nuxt
    ports:
      - '3000:3000'